[package]
name = "sprinkles"
version = "0.0.0-alpha1"
edition = "2024"

[dependencies]
ormlite = { version = "0.23.3", features = ["sqlite"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
zbus = { version = "5.7.1", features = ["tokio"] }
zbus_notification = "0.3.6"
